### ISSUE TITLE
gray HUD components in spectator mode when ingame snitch display enabled

### ISSUE THREAD

**Issue by Gjum** [MrLittleKitty/Snitch-Master#14]
Using 4a154d2 which has the fix for #4, I still get rendering issues for HUD components (chat, plugins loaded via FML):

![ingame snitch display disabled](https://cloud.githubusercontent.com/assets/2612164/21532819/6906532e-cd54-11e6-88de-4b44ec99b95f.png)
![ingame snitch display enabled](https://cloud.githubusercontent.com/assets/2612164/21532821/6b3775d8-cd54-11e6-9c6c-1cc40439665e.png)

(these screenshots are from spectator mode)

This issue also occurs with the code from before #4 was fixed.

**Comment by MrLittleKitty** [comment]
Try it again with the current version of the `featureUpdates` branch. I think it might be fixed because I am not able to replicate the bug.

**Comment by MrLittleKitty** [comment]
Can't duplicate and probably fixed.
