### ISSUE TITLE
Reverse scale text over snitches

### ISSUE THREAD

**Issue by awoo-civ** [MrLittleKitty/Snitch-Master#17]
Right now, as you approach a snitch, the text over it stays the same size, effectively getting bigger. What should happen is that the text decreases in size as the player approaches the snitch.
Journemap does this with its waypoint names, but *of course* it's not open source.

**Comment by MrLittleKitty** [comment]
Done as of guiUpgrades branch: https://github.com/MrLittleKitty/Snitch-Master/commit/68e75c6625fb21f3ffcc7f43b87d6957d09de4d8
