### ISSUE TITLE
Update snitch names on /janame

### ISSUE THREAD

**Issue by awoo-civ** [MrLittleKitty/Snitch-Master#19]
The /janame chat message exposes the location and group of the affected snitch in its [hover message](https://github.com/DevotedMC/JukeAlert/blob/master/src/main/java/com/untamedears/JukeAlert/command/commands/NameCommand.java#L54).

**Comment by MrLittleKitty** [comment]
Completed as of https://github.com/MrLittleKitty/Snitch-Master/commit/4c35a1720fbb04efb824ca68c12d010d6332220c.
