### ISSUE TITLE
JourneyMap Overlay broken on Fullscreen

### ISSUE THREAD

**Issue by notazed** [MrLittleKitty/Snitch-Master#22]
In version 1.0.9, the JourneyMap overlay feature works in the minimap, and also works on the fullscreen map the first time it's opened, but it disappears (only) from the fullscreen map if the map is toggled again. (journeymap-1.10.2-5.4.6)

PS: Appears seemingly random, actually. Sometimes moving fixes it, sometimes it doesn't...

**Comment by notazed** [comment]
Also, if you have your mouse hovering over the snitch field when you close the fullscreen map, the hovertext will be stuck in the minimap as well.

**Comment by Gjum** [comment]
> hovertext will be stuck in the minimap

pretty sure that's an issue inside journeymap.

**Comment by MrLittleKitty** [comment]
Almost all the problems with JourneyMap are going to be something internal to it that I can't fix
