### ISSUE TITLE
Can't toggle JourneyMap Overlay without Snitch Rendering enabled

### ISSUE THREAD

**Issue by notazed** [MrLittleKitty/Snitch-Master#23]
You can toggle JourneyMap overlay if Snitch Rendering is on, but you can't toggle the overlay when rendering is disabled. Yet, it still gives you 'overlay toggled' messages.

**Comment by Gjum** [comment]
bugs me as well. the problem is in the internal representation; toggling snitches on/off in-game toggles each group on/off instead of setting a global in-game rendering toggle like the map overlay has.

**Comment by MrLittleKitty** [comment]
Completed (probably?) as of https://github.com/MrLittleKitty/Snitch-Master/commit/70774c5c626bc0d7c7a749e26bcfaba6f5546a37
