### ISSUE TITLE
Can no longer remove Snitches/Lists

### ISSUE THREAD

**Issue by notazed** [MrLittleKitty/Snitch-Master#24]
You can no longer remove Snitches or Snitch Lists in v1.0.9, neither automatically *nor manually*.

**Comment by MrLittleKitty** [comment]
I personally haven't seen this. 

I'll look into it as I go about closing issues but it's not going to be at the top of the stack.

**Comment by notazed** [comment]
I'm sorry, it seems like the delete/remove buttons were considered it's own column and somehow got disabled in my settings... :I
