### ISSUE TITLE
Snitches added manually cannot change groups (without removing and adding them back).

### ISSUE THREAD

**Issue by notazed** [MrLittleKitty/Snitch-Master#25]
In version 1.0.9, if a new snitch was added manually, intentionally or accidentally, even on your own group, it'd by default go to the "Neutral" group.

It will not automatically update to the "Friendly" group once /jalist was updated by chat or by menu, however.

**Comment by Gjum** [comment]
can confirm this issue, it has existed across several versions already.

a workaround seems to be renaming the snitch, the resulting chat message will get picked up and update the snitch.

**Comment by MrLittleKitty** [comment]
This should be resolved as of https://github.com/MrLittleKitty/Snitch-Master/commit/bde51eab3b98561b43f7831f44e24ca48c6c174e
