### ISSUE TITLE
changing snitch lists through gui doesn't update snitches' assigned lists

### ISSUE THREAD

**Issue by Gjum** [MrLittleKitty/Snitch-Master#26]
Changing the sorting order etc. can change what group a snitch is assigned to, but it only applies on the next reload or rescan.

https://github.com/MrLittleKitty/Snitch-Master/blob/1.1.0/src/main/java/com/gmail/nuclearcat1337/snitch_master/gui/snitchliststable/SnitchListControlsColumn.java#L63

**Comment by MrLittleKitty** [comment]
Going to go ahead and close this because its not an issue :)
