### ISSUE TITLE
Snitches don't show up

### ISSUE THREAD

**Issue by OmerBenGera** [MrLittleKitty/Snitch-Master#31]
The snitches don't show up at all. I tried to toggle render, full snitch update, delete the folder and restart the client - nothing helps. The snitches also don't show up in the snitch list
What should I do?

**Comment by Tarenaran** [comment]
I'm also having this issue. Snitches only show up when I right click them. Do not show from /jalist.

**Comment by awoo-civ** [comment]
@MrLittleKitty 
Some context:
 - This is on civclassic (mc.civclassic.com)
 - It only broke after the admin enabled snitch culling, I haven't looked at the code too closely but maybe /jalist parsing is broken somehow?
 - There's no errors in the console.

**Comment by MrLittleKitty** [comment]
I came to the conclusion that it is because of snitch culling as well. I'll look more into it when I get a chance.

**Comment by Gjum** [comment]
imo this can be closed, just need to make a release with the fix

**Comment by MrLittleKitty** [comment]
@Gjum @iykHvfIvfR @OmerBenGera @Tarenaran 

A release is here: https://github.com/MrLittleKitty/Snitch-Master/releases/tag/1.2.0.pre
