### ISSUE TITLE
Disabling the in-game HUD (F1) while displaying snitches darkens the screen

### ISSUE THREAD

**Issue by awoo-civ** [MrLittleKitty/Snitch-Master#4]
Issue from Snitch Visualizer: https://github.com/waffle-stomper/Snitch-Visualizer/issues/2

**Comment by Gjum** [comment]
Might be related: sometimes the player hand will be transparent and shaded in the same color as the last drawn snitch.

*Edit:* Screenshot
![2016-12-04_03 27 16](https://cloud.githubusercontent.com/assets/2612164/21465023/331da13e-c991-11e6-9345-3f2ec54ff05c.png)

**Comment by MrLittleKitty** [comment]
What interesting timing for this issue as I actually just noticed this last night for the first time. I didn't realize at the time though that the cause was Snitch Master. I'll try and look into this when I get a chance but if anyone else finds a cause let me know.

**Comment by MrLittleKitty** [comment]
Fixed this.
