### ISSUE TITLE
Snitches.csv cannot exceed 8192 byte

### ISSUE THREAD

**Issue by Gjum** [MrLittleKitty/Snitch-Master#7]
I update the snitch list, which imports > 1000 snitches, all of them are saved correctly into the csv.
When I open up Minecraft again, this file is being read, but the line containing byte 8192 is cut off at that index and thus cannot be parsed into a snitch, crashing the mod.

**Comment by MrLittleKitty** [comment]
@Gjum 

Can you check if this is still happening after [this commit](https://github.com/MrLittleKitty/Snitch-Master/commit/4a154d297108abbbce1434398f5db34337d4f0f3)?

**Comment by Gjum** [comment]
Nope, still cuts off the file at the entry at byte 8192. It does not crash anymore though, just stops there.

Did you manage to reproduce it yourself?

**Comment by Gjum** [comment]
Fixed in latest version.
